### ISSUE TITLE
Track "Nodes" to allow for easier junctions and connections

### ISSUE THREAD

**Issue by Static-5** [Open-Source-Transport/roblox-path-plugin#5]
Possibly a better way to do this, but leave nodes at the end of a segment to allow for track to be branched off or into. Also allows to easily connect to segments

**Comment by anthony0br** [comment]
I think an option to leave nodes will suffice. You might already be able to do this by manually cloning them too. I believe there are only two nodes anyway since this uses cubic beziers, but I should check!

**Comment by arandomollie** [comment]
Believe #14 somewhat supersedes this as provides same functionality with less complexity
